<?php
/**
 * Copyright (C) 1997-2020 Reyesoft <info@reyesoft.com>.
 *
 * This file is part of Saldo.com.ar. Saldo.com.ar can not be copied and/or
 * distributed without the express permission of Reyesoft
 */

namespace BankAccounts\Mx;

/**
 * @see https://es.wikipedia.org/wiki/CLABE
 *
 * @internal
 */
final class BankNamesRepository
{
    public const NAMES = [
        '002' => 'BANAMEX',
        '006' => 'BANCOMEXT',
        '009' => 'BANOBRAS',
        '012' => 'BBVA BANCOMER',
        '014' => 'SANTANDER',
        '019' => 'BANJERCITO',
        '021' => 'HSBC',
        '030' => 'BAJÍO',
        '032' => 'IXE',
        '036' => 'INBURSA',
        '037' => 'INTERACCIONES',
        '042' => 'MIFEL',
        '044' => 'SCOTIABANK',
        '058' => 'BANREGIO',
        '059' => 'INVEX',
        '060' => 'BANSI',
        '062' => 'AFIRME',
        '072' => 'BANORTE',
        '102' => 'THE ROYAL BANK',
        '103' => 'AMERICAN EXPRESS',
        '106' => 'BAMSA',
        '108' => 'TOKYO',
        '110' => 'JP MORGAN',
        '112' => 'BMONEX',
        '113' => 'VE POR MAS',
        '116' => 'ING',
        '124' => 'DEUTSCHE',
        '126' => 'CREDIT SUISSE',
        '127' => 'AZTECA',
        '128' => 'AUTOFIN',
        '129' => 'BARCLAYS',
        '130' => 'COMPARTAMOS',
        '131' => 'FAMSA',
        '132' => 'BMULTIVA',
        '133' => 'ACTINVER',
        '134' => 'WAL-MART',
        '135' => 'NAFIN',
        '136' => 'INTERBANCO',
        '137' => 'BANCOPPEL',
        '138' => 'ABC CAPITAL',
        '139' => 'UBS BANK',
        '140' => 'CONSUBANCO',
        '141' => 'VOLKSWAGEN',
        '143' => 'CIBanco',
        '145' => 'BBASE',
        '147' => 'BANKAOOL',
        '148' => 'PagaTodo',
        '150' => 'BIM',
        '155' => 'ICBC',
        '156' => 'SABADELL',
        '166' => 'BANSEFI',
        '168' => 'HIPOTECARIA FEDERAL',
        '600' => 'MONEXCB',
        '601' => 'GBM',
        '602' => 'MASARI CB',
        '604' => 'C.B. INBURSA',
        '605' => 'VALUÉ',
        '606' => 'ESTRUCTURADORES',
        '607' => 'TIBER',
        '608' => 'VECTOR',
        '610' => 'B&B',
        '611' => 'INTERCAM',
        '613' => 'MULTIVA',
        '614' => 'ACCIVAL',
        '615' => 'MERRILL LYNCH',
        '616' => 'FINAMEX',
        '617' => 'VALMEX',
        '618' => 'ÚNICA',
        '619' => 'MAPFRE',
        '620' => 'PROFUTURO',
        '621' => 'CB ACTINBER',
        '622' => 'OACTIN',
        '623' => 'SKANDIA',
        '624' => 'CONSULTORÍA',
        '626' => 'CBDEUTSCHE',
        '627' => 'ZURICH',
        '628' => 'ZURICHVI',
        '629' => 'SU CASITA',
        '630' => 'C.B. INTERCAM',
        '631' => 'C.I. BOLSA',
        '632' => 'BULLTICK C.B.',
        '633' => 'STERLING',
        '634' => 'FINCOMUN',
        '636' => 'HDI SEGUROS',
        '637' => 'ORDER',
        '638' => 'AKALA',
        '640' => 'C.B. JP MORGAN',
        '642' => 'REFORMA',
        '646' => 'STP',
        '647' => 'TELECOMM',
        '648' => 'EVERCORE',
        '649' => 'SKANDIA',
        '651' => 'SEGMTY',
        '652' => 'ASEA',
        '653' => 'KUSPIT',
        '655' => 'SOFIEXPRESS',
        '656' => 'UNAGRA',
        '659' => 'OPCIONES EMPRESARIALES DEL NOROESTE',
        '670' => 'LIBERTAD',
        '674' => 'AXA',
        '677' => 'CAJA POP MEXICA',
        '679' => 'FND',
        '684' => 'TRANSFER',
        '901' => 'CLS',
        '902' => 'INDEVAL',
        '999' => 'N/A',
    ];
}
