on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2.33.0
      with:
        php-version: '7.4'
        extensions: xdebug
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache dependencies installed with composer
      uses: actions/cache@v4
      with:
        path: vendor
        key: php7.4-composer-locked-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          php7.4-composer-locked-
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: CI
      run: composer ci

    - name: Run tests
      run: composer coverage
